-- MySQL Script generated by MySQL Workbench
-- Fri Aug 24 21:05:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTADO` (
  `IDESTADO` INT NOT NULL,
  `NOME` VARCHAR(75) NULL,
  `UF` CHAR(2) NULL,
  PRIMARY KEY (`IDESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `IDCIDADE` INT NOT NULL,
  `NOME` VARCHAR(120) NULL,
  `ID_ESTADO` INT NOT NULL,
  PRIMARY KEY (`IDCIDADE`, `ID_ESTADO`),
  INDEX `FK_ESTADO_CIDADE_idx` (`ID_ESTADO` ASC),
  CONSTRAINT `FK_ESTADO_CIDADE`
    FOREIGN KEY (`ID_ESTADO`)
    REFERENCES `mydb`.`ESTADO` (`IDESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `IDUSER` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL,
  `CPF` VARCHAR(11) NULL,
  `NASCIMENTO` DATE NULL,
  `TELEFONE` VARCHAR(11) NULL,
  `ID_CIDADE` INT NOT NULL,
  `ID_ESTADO` INT NOT NULL,
  PRIMARY KEY (`IDUSER`, `ID_ESTADO`, `ID_CIDADE`),
  INDEX `FK_ESTADO_USER` (`ID_ESTADO` ASC),
  INDEX `FK_CIDADE_USER` (`ID_CIDADE` ASC),
  CONSTRAINT `FK_ESTADO_USER`
    FOREIGN KEY (`ID_ESTADO`)
    REFERENCES `mydb`.`ESTADO` (`IDESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CIDADE_USER`
    FOREIGN KEY (`ID_CIDADE`)
    REFERENCES `mydb`.`CIDADE` (`IDCIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCALP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOCALP` (
  `IDLOCALP` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL,
  `ENDERECO` VARCHAR(100) NULL,
  `ID_CIDADE` INT NOT NULL,
  `ID_ESTADO` INT NOT NULL,
  PRIMARY KEY (`IDLOCALP`, `ID_CIDADE`, `ID_ESTADO`),
  INDEX `FK_CIDADE_LOCALP` (`ID_CIDADE` ASC),
  INDEX `FK_ESTADO_LOCALP` (`ID_ESTADO` ASC),
  CONSTRAINT `FK_CIDADE_LOCALP`
    FOREIGN KEY (`ID_CIDADE`)
    REFERENCES `mydb`.`CIDADE` (`IDCIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ESTADO_LOCALP`
    FOREIGN KEY (`ID_ESTADO`)
    REFERENCES `mydb`.`ESTADO` (`IDESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARTIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PARTIDA` (
  `IDPARTIDA` INT NOT NULL AUTO_INCREMENT,
  `MODALIDADE` VARCHAR(100) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORARIO` TIME NOT NULL,
  `NRJOGADORES` INT NOT NULL,
  `PLACARTIME1` INT NULL,
  `PLACARTIME2` INT NULL,
  `ID_LOCALP` INT NOT NULL,
  PRIMARY KEY (`IDPARTIDA`, `ID_LOCALP`),
  INDEX `FK_LOCALP_PARTIDA` (`ID_LOCALP` ASC),
  CONSTRAINT `FK_LOCALP_PARTIDA`
    FOREIGN KEY (`ID_LOCALP`)
    REFERENCES `mydb`.`LOCALP` (`IDLOCALP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESCALACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESCALACAO` (
  `IDESCALACAO` INT NOT NULL AUTO_INCREMENT,
  `ID_USER` INT NOT NULL,
  `ID_PARTIDA` INT NOT NULL,
  PRIMARY KEY (`IDESCALACAO`, `ID_USER`, `ID_PARTIDA`),
  INDEX `FK_USER_ESCALACAO` (`ID_USER` ASC),
  INDEX `FK_PARTIDA_ESCALACAO` (`ID_PARTIDA` ASC),
  CONSTRAINT `FK_USER_ESCALACAO`
    FOREIGN KEY (`ID_USER`)
    REFERENCES `mydb`.`USER` (`IDUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PARTIDA_ESCALACAO`
    FOREIGN KEY (`ID_PARTIDA`)
    REFERENCES `mydb`.`PARTIDA` (`IDPARTIDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
