/* BACK UP DAS TABAELAS EM OUTRO BANCO DE DADOS */

CREATE DATABASE BACKUP_AJKS;

USE BACKUP_AJKS;

/*CRIANDO AS TABELAS PARA BACKUP DE DADOS */

CREATE TABLE BACKUP_DADOSPESSOAS(
	IDBACKUPDADOSPESSOAS INT PRIMARY KEY AUTO_INCREMENT,
	IDDADOSPESSOAS INT,
	NOME VARCHAR(45) NOT NULL,
	EMAIL VARCHAR(45)  NOT NULL,
	DATANASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CPF CHAR(14)  NOT NULL,
	CELULAR VARCHAR(14) NOT NULL,
	CEP CHAR (9) NOT NULL,
	RUA VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(8) NOT NULL,
	BAIRRO VARCHAR(25) NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

CREATE TABLE BACKUP_MOTORISTA(
	IDBACKUPMOTORISTA INT PRIMARY KEY AUTO_INCREMENT,
	IDMOTORISTA INT,
	NUMEROREGISTRO VARCHAR(10) NOT NULL,
	VALIDADE DATE NOT NULL,
	ID_DADOSPESSOAS INT,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

CREATE TABLE BACKUP_ADMIN(
	IDBACKUPADMIN INT PRIMARY KEY AUTO_INCREMENT,
	IDADMIN INT,
	SENHA VARCHAR (255),
	ID_DADOSPESSOAS INT,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

CREATE TABLE BACKUP_VIATURA(
	IDBACKUPVIATURA INT PRIMARY KEY AUTO_INCREMENT,
	IDVIATURA INT,
	TIPOVEICULO VARCHAR(45) NOT NULL,
	MARCA VARCHAR(25) NOT NULL,
	MODELO VARCHAR(25) NOT NULL,
	COR VARCHAR(25) NOT NULL,
	ANOFABRICACAO CHAR(4) NOT NULL,
	PLACA CHAR(8) NOT NULL,
	RENAVAN CHAR(11) NOT NULL,
	PASSAGEIROS CHAR(2) NOT NULL,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

CREATE TABLE BACKUP_VIAGENS(
	IDBACKUPVIAGENS INT PRIMARY KEY AUTO_INCREMENT,
	IDVIAGENS INT,
	CIDADE VARCHAR(25) NOT NULL,
	DATAHORAINICIO DATETIME NOT NULL,
	DATAHORAFINAL DATETIME NOT NULL,
	COR VARCHAR(15) NOT NULL,
	CEP CHAR(9) NOT NULL,
	RUA VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(8) NOT NULL,
	BAIRRO VARCHAR(25) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	DESCRICAO VARCHAR(200),
	ID_MOTORISTA INT,
	ID_VIATURA INT,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

CREATE TABLE BACKUP_PASSAGEIRO(
	IDBACKUPPASSAGEIRO INT PRIMARY KEY AUTO_INCREMENT,
	IDPASSAGEIRO INT,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);