DELIMITER $

USE AJKS

/* CRIANDO BACKUP PARA A INSERÇÃO DE DADOS NOVOS */
/*-----------------------------------------------------------------------------------------------------------*/

CREATE TRIGGER BACKUP_DADOSPESSOAS_I
AFTER INSERT ON DADOSPESSOAS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_DADOSPESSOAS VALUES(NULL,NEW.IDDADOSPESSOAS,NEW.NOME,
		NEW.EMAIL,NEW.DATANASCIMENTO,NEW.SEXO,NEW.CPF,NEW.CELULAR,NEW.CEP,NEW.RUA,
		NEW.NUMERO,NEW.BAIRRO,NEW.CIDADE,NEW.ESTADO,NOW(),CURRENT_USER(),'I');
END
$

CREATE TRIGGER BACKUP_MOTORISTA_I
AFTER INSERT ON MOTORISTA
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_MOTORISTA VALUES(NULL,NEW.IDMOTORISTA,NEW.NUMEROREGISTRO,NEW.VALIDADE,
		NEW.ID_DADOSPESSOAS,NOW(),CURRENT_USER(),'I');
END
$

CREATE TRIGGER BACKUP_ADMIN_I
AFTER INSERT ON ADMIN
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_ADMIN VALUES(NULL, NEW.IDADMIN,NEW.SENHA, NEW.ID_DADOSPESSOAS, NOW(),CURRENT_USER(),'I');
END
$

CREATE TRIGGER BACKUP_VIATURA_I
AFTER INSERT ON VIATURA
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_VIATURA VALUES(NULL, NEW.IDVIATURA,NEW.TIPOVEICULO, NEW.MARCA, NEW.MODELO,
		NEW.COR,NEW.ANOFABRICACAO,NEW.PLACA, NEW.RENAVAN,NEW.PASSAGEIROS,NOW(),CURRENT_USER(),'I');
END
$

CREATE TRIGGER BACKUP_VIAGENS_I
AFTER INSERT ON VIAGENS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_VIAGENS VALUES(NULL,NEW.IDVIAGENS, NEW.CIDADE,NEW.DATAHORAFINAL, NEW.DATAHORAFINAL,NEW.COR,
		NEW.CEP,NEW.RUA,NEW.NUMERO,NEW.BAIRRO,NEW.ESTADO,NEW.DESCRICAO, NEW.ID_MOTORISTA,
		 NEW.ID_VIATURA, NOW(),CURRENT_USER(),'I');
END
$

CREATE TRIGGER BACKUP_PASSAGEIRO_I
AFTER INSERT ON PASSAGEIRO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_PASSAGEIRO VALUES(NULL, NEW.IDPASSAGEIRO,NEW.ID_DADOSPESSOAS, NEW.ID_VIAGEM, NOW(),CURRENT_USER(),'I');
END
$

/* CRIANDO O BACKUP PARA A ATUALIZAÇÃO DE DADOS */
/*-----------------------------------------------------------------------------------------------------------*/

CREATE TRIGGER BACKUP_DADOSPESSOAS_U
BEFORE UPDATE ON DADOSPESSOAS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_DADOSPESSOAS VALUES(NULL,OLD.IDDADOSPESSOAS,OLD.NOME,
		OLD.EMAIL,OLD.DATANASCIMENTO,OLD.SEXO,OLD.CPF,OLD.CELULAR,OLD.CEP,OLD.RUA,
		OLD.NUMERO,OLD.BAIRRO,OLD.CIDADE,OLD.ESTADO,NOW(),CURRENT_USER(),'U');
END
$

CREATE TRIGGER BACKUP_MOTORISTA_U
BEFORE UPDATE ON MOTORISTA
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_MOTORISTA VALUES(NULL,OLD.IDMOTORISTA,OLD.NUMEROREGISTRO,OLD.VALIDADE,
		OLD.ID_DADOSPESSOAS,NOW(),CURRENT_USER(),'U');
END
$

CREATE TRIGGER BACKUP_ADMIN_U
BEFORE UPDATE ON ADMIN
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_ADMIN VALUES(NULL, OLD.IDADMIN,OLD.SENHA, OLD.ID_DADOSPESSOAS, NOW(),CURRENT_USER(),'U');
END
$

CREATE TRIGGER BACKUP_VIATURA_U
BEFORE UPDATE ON VIATURA
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_VIATURA VALUES(NULL, OLD.IDVIATURA,OLD.TIPOVEICULO, OLD.MARCA, OLD.MODELO,
		OLD.COR,OLD.ANOFABRICACAO,OLD.PLACA, OLD.RENAVAN,OLD.PASSAGEIROS,NOW(),CURRENT_USER(),'U');
END
$

CREATE TRIGGER BACKUP_VIAGENS_U
BEFORE UPDATE ON VIAGENS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_VIAGENS VALUES(NULL,OLD.CIDADE,OLD.DATAHORAFINAL, OLD.DATAHORAFINAL,OLD.COR,
		OLD.CEP,OLD.RUA,OLD.NUMERO,OLD.BAIRRO,OLD.ESTADO,OLD.DESCRICAO, OLD.ID_MOTORISTA, OLD.ID_VIATURA, NOW(),CURRENT_USER(),'U');
END
$


CREATE TRIGGER BACKUP_PASSAGEIRO_U
BEFORE UPDATE ON PASSAGEIRO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_PASSAGEIRO_U VALUES(NULL, OLD.IDPASSAGEIRO,OLD.ID_DADOSPESSOAS, OLD.ID_VIAGEM, NOW(),CURRENT_USER(),'U');
END
$
/* CRIANDO O BACKUP PARA DELETE  DE DADOS */
/*-----------------------------------------------------------------------------------------------------------*/

CREATE TRIGGER BACKUP_DADOSPESSOAS_D
BEFORE DELETE ON DADOSPESSOAS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_DADOSPESSOAS VALUES(NULL,OLD.IDDADOSPESSOAS,OLD.NOME,
		OLD.EMAIL,OLD.DATANASCIMENTO,OLD.SEXO,OLD.CPF,OLD.CELULAR,OLD.CEP,OLD.RUA,
		OLD.NUMERO,OLD.BAIRRO,OLD.CIDADE,OLD.ESTADO,NOW(),CURRENT_USER(),'D');
END
$

CREATE TRIGGER BACKUP_MOTORISTA_D
BEFORE DELETE ON MOTORISTA
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_MOTORISTA VALUES(NULL,OLD.IDMOTORISTA,OLD.NUMEROREGISTRO,OLD.VALIDADE,
		OLD.ID_DADOSPESSOAS,NOW(),CURRENT_USER(),'D');
END
$

CREATE TRIGGER BACKUP_ADMIN_D
BEFORE DELETE ON ADMIN
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_ADMIN VALUES(NULL, OLD.IDADMIN,OLD.SENHA,NOW(),CURRENT_USER(),'D');
END
$

CREATE TRIGGER BACKUP_VIATURA_D
BEFORE DELETE  ON VIATURA
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_VIATURA VALUES(NULL, OLD.IDVIATURA,OLD.TIPOVEICULO, OLD.MARCA, OLD.MODELO,
		OLD.COR,OLD.ANOFABRICACAO,OLD.PLACA, OLD.RENAVAN,OLD.PASSAGEIROS,NOW(),CURRENT_USER(),'D');
END
$

CREATE TRIGGER BACKUP_VIAGENS_D
BEFORE DELETE ON VIAGENS
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_VIAGENS VALUES(NULL, OLD.IDVIAGENS,OLD.CIDADE,OLD.DATAHORAINICIO, OLD.DATAHORAFINAL,OLD.COR,
		OLD.CEP,OLD.RUA,OLD.NUMERO,OLD.BAIRRO,OLD.ESTADO,OLD.DESCRICAO,  OLD.ID_MOTORISTA, OLD.ID_VIATURA, NOW(),CURRENT_USER(),'D');
END
$

CREATE TRIGGER BACKUP_PASSAGEIRO_D
BEFORE DELETE ON PASSAGEIRO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP_AJKS.BACKUP_PASSAGEIRO_D VALUES(NULL, OLD.IDPASSAGEIRO,OLD.ID_DADOSPESSOAS, OLD.ID_VIAGEM, NOW(),CURRENT_USER(),'D');
END
$