CREATE DATABASE FUTIBAS;

USE FUTIBAS;

CREATE TABLE DADOSPESSOAS (
	IDDADOSPESSOAS INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(45) NOT NULL,
	CPF CHAR(14) UNIQUE NOT NULL,
	EMAIL VARCHAR(45) UNIQUE NOT NULL,
	CELULAR VARCHAR(14) UNIQUE NOT NULL,
	DATANASCIMENTO DATE NOT NULL,
);

CREATE TABLE JOGADOR (
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	ID_DADOSPESSOAS INT
);

CREATE TABLE ADM (
	IDADM INT PRIMARY KEY AUTO_INCREMENT,
	ID_DADOSPESSOAS INT
);

CREATE TABLE QUADRA (
	IDQUADRA INT PRIMARY KEY AUTO_INCREMENT,
	NOMEQUADRA VARCHAR (45),
	COBERTA CHAR (1),
	ID_DADOSPESSOAS INT,
	ENDERECO VARCHAR (100),
	CIDADE VARCHAR (100),
	UF CHAR (2)
);

CREATE TABLE PARTIDA (
	IDPARTIDA INT PRIMARY KEY AUTO_INCREMENT,
	ID_ADM INT,
	ID_QUADRA INT,
	DATA DATE,
	HORARIO TIME
);

CREATE TABLE JOGADOR_X_PARTIDA (
	IDJOGADORXPARTIDA INT PRIMARY KEY AUTO_INCREMENT,
	ID_JOGADOR INT,
	ID_PARTIDA INT
);